#logging.level:
#  org.hibernate:
#    SQL: DEBUG
#    type.descriptor.sql.BasicBinder: TRACE
#  org.springframework:
#    jdbc.core:
#      JdbcTemplate: DEBUG
#      StatementCreatorUtils: TRACE

spring:
  jpa:
    hibernate:
      ddl-auto: create
#    properties.hibernate:
#      type: trace
#      show_sql: true
#      format_sql: true
#      use_sql_comments: false
    defer-datasource-initialization: on
  sql.init.mode: always
springfox:
  documentation.enabled: true