server:
  port: 8080
  ssl.enabled: false
  servlet.encoding:
    charset: UTF-8
    enabled: true
    force: true

spring:
  main.banner-mode: off
  profiles.active:

  mvc:
    pathmatch.matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:mariadb://localhost:3306/icdev?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
    username: root
    password: 123456

  jpa:
    hibernate.ddl-auto: update
    open-in-view: false

  jackson:
    time-zone: GMT+8
    default-property-inclusion: non_empty
    deserialization:
      fail_on_unknown_properties: false
    mapper:
      default-view-inclusion: true
