spring:
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mariadb://localhost:3307/icdev?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
    username: root
    password: root
    initialization-mode: never
