spring:
  jpa:
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: off

  sql.init.mode: never

  datasource:
    url: jdbc:mariadb://localhost:3306/hcta?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
    username: root
    password: 123456

springfox:
  documentation.enabled: false
